name: Docker Image CI/CD

# Triggers the workflow on pushes to the 'main' branch
on:
  push:
    branches: ["main"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    # Permissions are required for the GITHUB_TOKEN if using GitHub's package registry,
    # but still good practice for general CI/CD.
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        # This action uses your stored secrets for secure authentication
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx (for multi-platform builds)
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/docker-demo-web # Replace with your actual repo name
          # Automatically generates tags based on git branch/sha, e.g., latest, <sha>
          tags: |
            type=ref,event=branch
            type=sha
            type=semver,pattern={{version}}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . # Uses the current directory as the build context
          file: ./Dockerfile # Specifies the Dockerfile path
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
